squaw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("sqwbase.urls")),
]

sqwbase/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.static import serve

from . import views

app_name = "sqwbase"
urlpatterns = [
    path("", views.index, name="index"),
    path("workflow/<int:workflow_id>/", views.workflow, name="workflow"),
    path("workflow/<int:workflow_id>/molecule/<int:molecule_id>",
         views.mol_workflow, name="mol_workflow"),
    #path("calculation/<int:pk>", views.CalculationDetail.as_view(),
    #     name="calculation"),
    #path("molecule/<int:pk>", views.MoleculeDetail.as_view(),
    #     name="molecule"),
    path("calculation/<int:calculation_id>/", views.calculation, name="calculation"),
    path("molecule/<int:molecule_id>/", views.molecule, name="molecule"),
    path("molecules/", views.MoleculeList.as_view(), name="molecules"),
    path("workflows/", views.WorkflowList.as_view(), name="workflows"),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r"^media/(?P<path>.*)$", serve, {
            "document_root": settings.MEDIA_ROOT,
        }),
    ]

sqwbase/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey


def rename_pdb(instance, filename):
    if isinstance(instance, Molecule):
        prefix = "molecule_"
    elif isinstance(instance, Calculation):
        prefix = "calc_"
    else:
        prefix = ""
    save_to = "pdbs/" + f"{prefix}pk{instance.pk}_" + filename
    return save_to


class Project(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Workflow(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)

    def __str__(self):
        #return "{} - {}".format(self.project.name, self.name)
        return self.name


class Task(MPTTModel):
    workflow = models.ForeignKey(Workflow, blank=True, null=True,
                                 on_delete=models.CASCADE)
    parent = TreeForeignKey("self", blank=True, null=True,
                            on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    analysis = models.TextField(blank=True)

    def __str__(self):
        return self.title


class Molecule(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    workflow = models.ManyToManyField(Workflow)
    description = models.TextField(blank=True)
    pdb_file = models.FileField(blank=True, upload_to=rename_pdb)

    def __str__(self):
        return self.name


class Method(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Basis(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Program(models.Model):
    name = models.CharField(max_length=200)
    version = models.CharField(max_length=20)

    def __str__(self):
        return "{} {}".format(self.name, self.version)


class SolventModel(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Calculation(models.Model):
    title = models.CharField(max_length=250)
    task = TreeForeignKey(Task, on_delete=models.CASCADE)
    molecule = models.ForeignKey(Molecule, on_delete=models.CASCADE)
    local_path = models.CharField(max_length=250, blank=True)
    remote_path = models.CharField(max_length=250, blank=True)
    calculation_comment = models.TextField(blank=True)
    solvent = models.ForeignKey(SolventModel, blank=True,
                                on_delete=models.CASCADE)

    method = models.ForeignKey(Method, null=True, blank=True,
                               on_delete=models.CASCADE)
    basis = models.ForeignKey(Basis, null=True, blank=True,
                              on_delete=models.CASCADE)
    program = models.ForeignKey(Program, null=True, blank=True,
                                on_delete=models.CASCADE)
    pdb_file = models.FileField(blank=True, upload_to=rename_pdb)
    result = models.BooleanField()

    def __str__(self):
        return self.title


class MoleculeTaskMatrix(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ManyToManyField(Task)
    molecule = models.ManyToManyField(Molecule)

sqwbase/views.py
from django.db.models import prefetch_related_objects
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import (Calculation, Molecule, Project,
                     Task, Workflow)


def index(request):
    fields = ("project", "workflow")
    molecules = Molecule.objects.prefetch_related(*fields).all()
    context = {
                "molecules": molecules,
    }
    return render(request, "sqwbase/index.html", context)


def workflow(request, workflow_id):
    workflow = Workflow.objects.get(pk=workflow_id)
    tasks = list()
    for t in Task.objects.filter(workflow__pk=workflow_id):
        t.calculations = Calculation.objects.filter(task=t)
        tasks.append(t)
    context = {
                "workflow": workflow,
                "tasks": tasks,
    }
    return render(request, "sqwbase/workflow.html", context)


def mol_workflow(request, workflow_id, molecule_id):
    # https://stackoverflow.com/questions/31172680
    # prefetch geht nicht weil task kein workflow foreign key hat
    molecule = Molecule.objects.select_related("project").get(pk=molecule_id)
    workflow = Workflow.objects.get(pk=workflow_id)
    tasks = list()
    for t in Task.objects.filter(workflow__pk=workflow_id):
        filters = {
            "task": t,
            "molecule": molecule,
        }
        t.calculations = Calculation.objects.filter(**filters)
        tasks.append(t)
    context = {
                "molecule": molecule,
                "workflow": workflow,
                "tasks": tasks,
    }
    return render(request, "sqwbase/mol_workflow.html", context)


def calculation(request, calculation_id):
    calculation = Calculation.objects.get(pk=calculation_id)
    if calculation.pdb_file:
        with open(calculation.pdb_file.path) as handle:
            pdb = handle.read()
    else:
        pdb = False

    context = {
        "calculation": calculation,
        "pdb": pdb,
    }
    return render(request, "sqwbase/calculation_detail.html", context)


#class CalculationDetail(DetailView):
#    model = Calculation


class MoleculeDetail(DetailView):
    model = Molecule


def molecule(request, molecule_id):
    molecule = Molecule.objects.get(pk=molecule_id)
    if molecule.pdb_file:
        with open(molecule.pdb_file.path) as handle:
            pdb = handle.read()
    else:
        pdb = False

    context = {
        "molecule": molecule,
        "pdb": pdb,
    }
    return render(request, "sqwbase/molecule_detail.html", context)


class MoleculeList(ListView):
    model = Molecule


class WorkflowList(ListView):
    model = Workflow

sqwbase/templates/sqwbase/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'sqwbase/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'sqwbase/css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'sqwbase/font-awesome/css/fontawesome-all.min.css' %}">
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a href="{% url 'sqwbase:index' %}" class="navbar-brand">Home</a>
          <div class="collapse navbar-collapse">
            <div class="navbar-nav">
              <a href="{% url 'sqwbase:molecules' %}" class="nav-link">Molecules</a>
              <a href="{% url 'sqwbase:workflows' %}" class="nav-link">Workflows</a>
              <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
            </div>
          </div>
        </nav>
        {% block content %}
        {% endblock %}
        </div>
      </div>
    </div>

    <script src="{% static 'sqwbase/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'sqwbase/js/popper.js' %}"></script>
    <script src="{% static 'sqwbase/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'sqwbase/js/clipboard.min.js' %}"></script>
    <script>
      var clipboard = new Clipboard(".copybtn");
    </script>
</html>

sqwbase/templates/sqwbase/calculation_detail.html
{% extends "sqwbase/base.html" %}
{% load static %}

{% block title %}
 {{ calculation.molecule }} - {{ calculation.title }}
{% endblock %}

{% block content %}
  <h1>{{ calculation.molecule }} - {{ calculation.title }}</h1>
  <div class="row">
  <div class="col-md-6">
  <table class="table">
    <tr>
      <th>Task:</th>
      <td>{{ calculation.task }}</td>
    </tr>
    <tr>
      <th>Level:</th>
      <td>{{ calculation.method }}/{{ calculation.basis }}</td>
    </tr>
    <tr>
      <th>Solvent:</th>
      <td>{{ calculation.solvent }}</td>
    </tr>
    <tr>
      <th>Local:</th>
      <td id="localpath">{{ calculation.local_path }}</td>
    </tr>
    <tr>
      <th>Remote:</th>
      <td id="remotepath">{{ calculation.remote_path }}</td>
    </tr>
    <tr>
      <th>Comment:</th>
      <td>{{ calculation.calculation_comment }}</td>
    </tr>
    <tr>
      <th>Program:</th>
      <td>{{ calculation.program }}</td>
    </tr>
  </table>
  <a href="{% url 'admin:sqwbase_calculation_change' calculation.pk %}"><i class="fa fa-edit"></i> Edit</a>
  </div>



  {% if pdb %}
  <div class="col-md-6">
  <script src="{% static 'sqwbase/js/ngl.js' %}"></script>
  <script>
    const pdb_str = `{{ pdb }}`;
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile( new Blob([pdb_str], {type: 'text/plain'}),
                     { ext:'pdb', defaultRepresentation: true }
      );
    });
  </script>
  <div id="viewport" style="width:500px; height:500px;"></div>
  <a href="/media/{{ calculation.pdb_file.url }}" download>Download PDB</a>
  </div>
  {% endif %}
  </div>
{% endblock %}

sqwbase/templates/sqwbase/index.html
{% extends "sqwbase/base.html" %}

{% block title %}
 squaw - Home
{% endblock %}

{% block content %}
<h1>Projects</h1>

{% regroup molecules|dictsort:"project.name" by project as project_list %}
{% comment %}
{% for project in project_list %}
<h2>{{ project.grouper }}</h2>
    {% for molecule in project.list %}
        <h3>{{ molecule }}</h3>
        <!--<p class="text-info">{{ molecule.description }}</p>-->
        <ol>
            {% for workflow in molecule.workflow.all %}
            <li><a href="{% url 'sqwbase:mol_workflow' workflow.id molecule.id %}">{{ workflow }}</a></li>
            {% endfor %}
        </ol>
    {% endfor %}
{% endfor %}
{% endcomment %}

{% for project in project_list %}
<h2>{{ project.grouper }}</h2>
    <table class="table">
        <tr>
            <th>Molecule</th>
            <th>Workflows</th>
        </tr>
    {% for molecule in project.list %}
      <tr>
        <td>
            <a href="{% url 'sqwbase:molecule' molecule.pk %}">{{ molecule }}</a>
        </td>
        <td>
          {% for workflow in molecule.workflow.all %}
            <a href="{% url 'sqwbase:mol_workflow' workflow.id molecule.id %}">
                {{ workflow.name }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </td>
      </tr>
    {% endfor %}
    </table>
{% endfor %}

{% endblock %}

sqwbase/templates/sqwbase/mol_workflow.html
{% extends "sqwbase/base.html" %}
{% load sqwbase_extras %}

{% block title %}
 {{ molecule.name }} - {{ workflow.name }}
{% endblock %}

{% block content %}
<h1><a href="{% url 'sqwbase:molecule' molecule.id %}">{{ molecule }}</a>: {{ molecule.project }}
    - <a href="{% url 'sqwbase:workflow' workflow.id %}">{{ workflow.name }}</a>
</h1>
<!--<p class="text-info">{{ molecule.description }}</p>-->

{% load mptt_tags %}
    {% recursetree tasks %}
        {{ node.title|wrap_heading:node.level|safe }}
        <span class="text-info">{{ node.description }}</span>
        {% if node.calculations %}
        <table class="table">
            <thead class="thead-dark">
              <tr>
                 <th class="col-md-5">Level</th>
                 <th class="col-md-5">Title</th>
                 <th class="col-md-1">Result</th>
                 <th class="col-md-1">Edit</th>
              </tr>
            </thead>
            {% for calc in node.calculations %}
            <tr data-toggle="collapse" data-target="#coll{{ calc.id }}">
                <td>{{ calc.method }}/{{ calc.basis }}/{{ calc.solvent }}</td>
                <td><a href="{% url 'sqwbase:calculation' calc.id %}">{{ calc.title }}</a></td>
                <td><i class="fa fa-{% if calc.result %}check{% else %}times{% endif %}"></i></td>
                <td><a href="{% url 'admin:sqwbase_calculation_change' calc.id %}"><i class="fa fa-edit"></i></a></td>
            </tr>
            <tbody class="collapse table-sm workflow-detail" id="coll{{ calc.id }}">
                <tr>
                    <th>Local:</th>
                    <td id="localpath{{ calc.id }}">{{ calc.local_path }}</td>
                    {% if calc.local_path %}
                    <td>
                      <button class="copybtn btn" data-clipboard-action="copy" data-clipboard-target="#localpath{{ calc.id }}">Copy</button>
                    </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Remote:</th>
                    <td id="remotepath{{ calc.id }}">{{ calc.remote_path }}</td>
                    {% if calc.remote_path %}
                    <td>
                      <button class="copybtn btn" data-clipboard-action="copy" data-clipboard-target="#remotepath{{ calc.id }}">Copy</button>
                    </td>
                    {% endif %}
                </tr>
                <tr>
                    <th>Comment:</th>
                    <td>{{ calc.calculation_comment }}</td>
                </tr>
            </tbody>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <a href="{% url 'admin:sqwbase_calculation_add' %}?molecule={{ molecule.pk }}&task={{ node.pk }}"><i class="fa fa-plus"></i></a>
                </td>
            </tr>
        </table>
        {% else %}
        <p><a href="{% url 'admin:sqwbase_calculation_add' %}?molecule={{ molecule.pk }}&task={{ node.pk }}">(<i class="fa fa-plus"></i> Add first calculation)</a></p>
        {% endif %}
            {% if not node.is_leaf_node %}
                    {{ children }}
            {% endif %}
    {% endrecursetree %}
{% endblock %}

sqwbase/templates/sqwbase/molecule_detail.html
{% extends "sqwbase/base.html" %}
{% load static %}

{% block title %}
 {{ molecule.name }}
{% endblock %}

{% block content %}
  <h1>Molecule {{ molecule.name }}</h1>
  <div class="row">
  <div class="col-md-5">
  <table class="table">
    <tr>
      <th>Project:</th>
      <td>{{ molecule.project }}</td>
    </tr>
    <tr>
      <th>Workflows:</th>
      <td>
        {% for workflow in molecule.workflow.all %}
        <a href="{% url 'sqwbase:mol_workflow' workflow.id molecule.id %}">{{ workflow.name }}</a><br />
        {% endfor %}
      </td>
    </tr>
    <tr>
      <th>Description:</th>
      <td>{{ molecule.description }}</td>
    </tr>
  </table>
  <a href="{% url 'admin:sqwbase_molecule_change' molecule.pk %}"><i class="fa fa-edit"></i> Edit</a>
  </div>

  {% if pdb %}
  <div class="col-md-7">
  <script src="{% static 'sqwbase/js/ngl.js' %}"></script>
  <script>
    const pdb_str = `{{ pdb }}`;
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile( new Blob([pdb_str], {type: 'text/plain'}),
                     { ext:'pdb', defaultRepresentation: true }
      );
      stage.autoView();
    });
  </script>
  <div id="viewport" style="width:600px; height:600px;"></div>
  <a href="/media/{{ molecule.pdb_file.url }}" download>Download PDB</a>
  </div>
  {% endif %}
  </div>
{% endblock %}

sqwbase/templates/sqwbase/molecule_list.html
{% extends "sqwbase/base.html" %}
{% load static %}

{% block title %}
 Molecules
{% endblock %}

{% block content %}
{% regroup object_list|dictsort:"project.name" by project as by_project %}
{% for project in by_project %}
<h1>{{ project.grouper }}</h1>
<table class="table">
  <tr>
      <th class="col-md-4">Molecule</th>
      <th class="col-md-8">Description</th>
   </tr>
{% for molecule in project.list %}
  <tr>
      <td><a href="{% url 'sqwbase:molecule' molecule.pk %}">{{ molecule.name }}</a></td>
      <td>{{ molecule.description }}</td>
  </tr>
{% endfor %}
</table>
{% endfor %}
{% endblock %}

sqwbase/templates/sqwbase/workflow.html
{% extends "sqwbase/base.html" %}
{% load sqwbase_extras admin_urls markdownify %}

{% block title %}
 {{ workflow.name }}
{% endblock %}

{% block content %}
<h1>{{ workflow.project }} - {{ workflow.name }}</h1>
{% load mptt_tags %}

{% recursetree tasks %}
{{ node.title|wrap_heading:node.level|safe }}
<p class="text-info">{{ node.description }}</p>
  {% if node.analysis %}
  <strong>Analysis:</strong>
  {{ node.analysis|markdownify }}
  {% endif %}
  {% if not node.is_leaf_node %}
    {{ children }}
  {% endif %}
{% endrecursetree %}

<a href="{% url 'admin:sqwbase_workflow_change' workflow.pk %}"><i class="fa fa-edit"></i> Edit</a>

{% endblock %}

sqwbase/templates/sqwbase/workflow_list.html
{% extends "sqwbase/base.html" %}
{% load static %}

{% block title %}
 Workflows
{% endblock %}

{% block content %}
{% regroup object_list by project as by_project %}
{% for project in by_project %}
<h1>{{ project.grouper }}</h1>
<ol>
{% for workflow in project.list %}
  <li><a href="{% url 'sqwbase:workflow' workflow.id %}">{{ workflow.name }}</a></td>
{% endfor %}
</ol>
{% endfor %}
{% endblock %}